---

- name: ssh_hardening
  src: https://github.com/dev-sec/ansible-collection-hardening.git
  scm: git

- name: os_hardening
  src: https://github.com/dev-sec/ansible-collection-hardening.git
  scm: git

- src: arillso.logrotate

- src: geerlingguy.repo-epel

- src: geerlingguy.ntp

- name: motd
  src: https://github.com/justereseau/ansible-role-linux-motd.git
  scm: git

- name: ansible-disable-selinux
  src: https://github.com/stardata/ansible-disable-selinux.git
  scm: git

- name: ansible-resolv
  src: https://github.com/ahuffman/ansible-resolv
  scm: git
